version: "3.9"

services:
  neo4j:
    image: neo4j:5.20 # use the latest stable version
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH} 
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    env_file:
      - .env  

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: